version: '3.7'

services:
  twspace-dl:
    image: ghcr.io/holoarchivists/twspace-dl:latest
    # build: .
    restart: "no"
    env_file: .env
    volumes:
      - ./:/output
    entrypoint: [ "/usr/bin/dumb-init", "--", "sh" ]
    command: [ "monitor.sh" ]
    # logging:
    #   driver: "gelf"
    #   options:
    #     gelf-address: "udp://127.0.0.1:12201"
